name: Windows Server

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Windows Server
      run: |
        # Commandes pour installer et configurer le serveur
        Install-WindowsFeature -name Web-Server -IncludeManagementTools

    - name: Enable RDP (Remote Desktop Protocol)
      run: |
        # Activer le Bureau à distance (RDP)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
        # Assurez-vous que le pare-feu autorise les connexions RDP
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Windows Server
      run: |
        # Démarrer le service IIS
        Start-Service W3SVC

    - name: Test server
      run: |
        # Vérifier que le serveur IIS fonctionne correctement
        Invoke-WebRequest -Uri http://localhost -UseBasicParsing

    - name: Display public IP
      run: |
        # Afficher l'IP publique du serveur
        $ip = (Invoke-RestMethod -Uri http://ipinfo.io/ip).Trim()
        Write-Host "Public IP: $ip"
